export enum Routes {
  Home = '/home',
  Recipes = '/recipes',
  RecipesBySearch = '/recipes/search',
  RecipesCreate = '/recipes/create',
  RecipesEdit = '/recipes/edit/:id',
  Ners = '/ners',
  NersCreate = '/ners/create',
  NersEdit = '/ners/edit/:id',
  Directions = '/directions',
  DirectionsCreate = '/directions/create',
  DirectionsEdit = '/directions/edit/:id',
  Ingredients = '/ingredients',
  IngredientsCreate = '/ingredients/create',
  IngredientsEdit = '/ingredients/edit/:id',
}
